import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

// This component is used to test whether you've succesfully 
// connected to the MongoDB database.
export default function TestDB() {
  const [posts, setPosts] = useState([]);
  const [body, setBody] = useState("");
  const [author, setAuthor] = useState("");
  const [error, setError] = useState(false);

  const handleLoad = async () => {
    try {
      const res = await fetch("/api/posts", {
        method: "GET",
      });
      console.log(res);
      if (res.status === 200) {
        const data = await res.json();
        setPosts(data);
      }
    } catch (e) {
      setError(true);
    }
  };

  useEffect(() => {
    handleLoad();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:container mx-auto">
        {/* ***TODO: Map through every post fetched from the database (instead of just one).*** */}
        {posts[0] ? (
          <>
            {/* HTML for a single post */}
            <div className="w-[50rem] mx-auto p-4 mb-4 rounded text-center">
              <div className="text-xl font-bold mb-4">
                <h2 className="text-2xl font-bold">
                  "{posts[0].title}" by {posts[0].author}
                </h2>
              </div>
              <p>{posts[0].body}</p>
            </div>
          </>
        ) : (
          <p className="text-center">Loading First Post...</p>
        )}
        {error && <h1 className="text-red-500">Connection Failed</h1>}
      </main>
    </>
  );
}
